[theme]
base = "dark"
primaryColor = "#22a7f0"
backgroundColor = "#0e1624"
secondaryBackgroundColor = "#172236"
textColor = "#f5f7fa"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
